# Z_J_gw_A_lo: zabbix-agent active checks via local zabbix-java-gateway
# https://blog.zabbix.com/new-monitoring-possibilities-for-java-applications-in-zabbix-3-4/5972/

UserParameter=z_java_gw_adapter_lo[*], /usr/local/bin/zabbix_java_gw_adapter localhost $1 "$2" $3 $4 | sed "s/,\"response\":\"success\"//"
